### ISSUE TITLE
Create a scoreboard

### ISSUE THREAD

**Issue by Rednaxela700** [infoshareacademy/jfdd13-dreamteam#18]
Player can put his/her name/score on it

**Comment by michal-kusnierz** [comment]
player adds his name only if his score gives him place between 1 and 10?

**Comment by Rednaxela700** [comment]
Good point, I don't have direct access to web right now. But I'll give it a try offline. Any ideas on score data structure? Obj array or what? Maybe @aszablowski, could give us a tip 🆘

**Comment by Rednaxela700** [comment]
created a small script for saving and displaying scores. Basic logic is set and good to go. For further information please checkout scoreboard branch and it's pull request.
